version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: finance-control-api:dev
    environment:
      CONFIG_FILE: /app/config/local_credentials.yaml
      APP_ENVIRONMENT: development
      AWS_REGION: us-east-1
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
      localstack:
        condition: service_healthy
    volumes:
      - ./config/local_credentials.yaml:/app/config/local_credentials.yaml:ro
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: finance-control
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:2.3
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sqs,cognito-idp
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: localstack
    volumes:
      - "./scripts/localstack:/etc/localstack/init/ready.d"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "awslocal", "sqs", "list-queues"]
      interval: 15s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
      args:
        VITE_API_URL: http://localhost:8080/api/v1
    image: finance-control-frontend:dev
    ports:
      - "5173:80"
    depends_on:
      api:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
