# syntax=docker/dockerfile:1

FROM golang:1.24 AS builder
WORKDIR /workspace

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bootstrap ./cmd/lambdas/transaction_processor

FROM public.ecr.aws/lambda/provided:al2
ENV CONFIG_FILE=/var/task/config/local_credentials.yaml
COPY config/local_credentials.yaml /var/task/config/local_credentials.yaml
COPY --from=builder /workspace/bootstrap /var/task/bootstrap
CMD ["bootstrap"]
