app:
  environment: homolog
  port: 8080
mongo:
  uri: mongodb://documentdb-endpoint:27017
  database: finance-control
  usernameParameter: /finance-control/homolog/mongo/username
  passwordParameter: /finance-control/homolog/mongo/password
aws:
  region: us-east-1
  useLocalstack: false
  endpoint: ""
  s3:
    bucket: finance-control-receipts-homolog
  sqs:
    queueName: finance-transactions-queue-homolog
    queueUrl: https://sqs.us-east-1.amazonaws.com/000000000000/finance-transactions-queue-homolog
  cognito:
    userPoolId: us-east-1_example
    clientId: example-client-id
    domain: https://auth-homolog.example.com
auth:
  mode: cognito
security:
  allowedOrigins:
    - https://app-hml.example.com
  encryptionKeyParameter: /finance-control/homolog/encryption/aes
queue:
  transactionQueue: finance-transactions-queue-homolog
storage:
  receiptBucket: finance-control-receipts-homolog
local:
  credentialsFile: ""  # não utilizado em homolog; secrets vêm do Parameter Store/Secrets Manager
