app:
  environment: development
  port: 8080
mongo:
  uri: mongodb://mongo:27017
  database: finance-control
aws:
  region: us-east-1
  useLocalstack: true
  endpoint: http://localstack:4566
  accessKeyId: localstack
  secretAccessKey: localstack
  s3:
    bucket: finance-control-receipts
  sqs:
    queueName: finance-transactions-queue
    queueUrl: http://localstack:4566/000000000000/finance-transactions-queue
  cognito:
    userPoolId: local-user-pool
    clientId: local-client-id
    domain: http://localhost:4566
auth:
  mode: local
security:
  allowedOrigins:
    - http://localhost:5173
  encryptionKey: "base64-encoded-32-byte-key"
queue:
  transactionQueue: finance-transactions-queue
storage:
  receiptBucket: finance-control-receipts
local:
  credentialsFile: config/local_credentials.yaml
  authUsers:
    - username: demo@local.dev
      password: DemoPass123!
      email: demo@local.dev
      name: Demo User
      defaultCurrency: USD
      cognitoSub: local-demo-user
