app:
  environment: development
  port: 8080
mongo:
  uri: mongodb://mongo:27017
  database: financial-control
aws:
  region: us-east-1
  useLocalstack: true
  endpoint: http://localstack:4566
  accessKeyId: localstack
  secretAccessKey: localstack
  s3:
    bucket: financial-control-receipts
  sqs:
    queueName: financial-transactions-queue
    queueUrl: http://localstack:4566/000000000000/financial-transactions-queue
    deadLetterQueueName: financial-transactions-dlq
    deadLetterQueueUrl: http://localstack:4566/000000000000/financial-transactions-dlq
  cognito:
    userPoolId: local-user-pool
    clientId: local-client-id
    domain: http://localhost:4566
auth:
  mode: local
security:
  allowedOrigins:
    - http://localhost:5173
  encryptionKey: "base64-encoded-32-byte-key" # usar AWS Secrets Manager em homolog/prod
queue:
  transactionQueue: financial-transactions-queue
storage:
  receiptBucket: financial-control-receipts
local:
  credentialsFile: config/local_credentials.yaml
  authUsers:
    - username: teste@gmail.com
      password: Teste2024!
      email: teste@gmail.com
      name: Usuário Teste
      defaultCurrency: BRL
      cognitoSub: local-teste-user
