app:
  environment: production
  port: 8080
mongo:
  uri: mongodb://documentdb-endpoint:27017
  database: financial-control
  usernameParameter: /financial-control/production/mongo/username
  passwordParameter: /financial-control/production/mongo/password
aws:
  region: us-east-1
  useLocalstack: false
  endpoint: ""
  s3:
    bucket: financial-control-receipts
  sqs:
    queueName: financial-transactions-queue
    queueUrl: https://sqs.us-east-1.amazonaws.com/123456789012/financial-transactions-queue
  cognito:
    userPoolId: us-east-1_XXXXXXXXX
    clientId: 1234567890abcdef
    domain: https://auth-prod.example.com
auth:
  mode: cognito
security:
  allowedOrigins:
    - https://app.example.com
  encryptionKeyParameter: /financial-control/production/encryption/aes
  tls:
    termination: alb
queue:
  transactionQueue: financial-transactions-queue
storage:
  receiptBucket: financial-control-receipts
