app:
  environment: production
  port: 8080
  https:
    enabled: true
    redirect: true
    certFile: "/etc/ssl/certs/api.crt"
    keyFile: "/etc/ssl/private/api.key"
mongo:
  uri: mongodb://mongo:27017
  database: finance-control
aws:
  region: us-east-1
  useLocalstack: false
  endpoint: ""
  accessKeyId: ""
  secretAccessKey: ""
  s3:
    bucket: finance-control-receipts
  sqs:
    queueName: finance-transactions-queue
    queueUrl: https://sqs.us-east-1.amazonaws.com/123456789012/finance-transactions-queue
  cognito:
    userPoolId: us-east-1_XXXXXXXXX
    clientId: 1234567890abcdef
    domain: https://your-domain.auth.us-east-1.amazoncognito.com
auth:
  mode: cognito
security:
  allowedOrigins:
    - https://your-frontend-domain.com
  encryptionKey: "your-production-encryption-key-base64"
queue:
  transactionQueue: finance-transactions-queue
storage:
  receiptBucket: finance-control-receipts
